In [5]:
import numpy as np

A = np.array([[1,2,3], [1,2,3], [1,2,3]])
b = np.array([4,5,6])

print(A@b)

np.einsum('ij,j->i', A, b)

[32 32 32]


array([32, 32, 32])

In [6]:
def cross_product(a,b):
    return np.array([a[1]*b[2] - a[2]*b[1],
                     a[2]*b[0] - a[0]*b[2],
                     a[1]*b[0] - a[0]*b[1]])

cross_product(np.array([1,2,3]), np.array([4,5,6]))

array([-3,  6,  3])

In [7]:
%timeit cross_product(np.array([1,2,3]), np.array([4,5,6]))

5.74 μs ± 655 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
%timeit np.cross(np.array([1,2,3]), np.array([4,5,6]))

61.5 μs ± 4.34 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [12]:
a = np.random.random(10000000)
for i in range(len(a)):
    a[i] = a[i] * 2

In [13]:
a = np.random.random(10000000)

a = a*2